/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public final class EnumInfoType {
  public final static EnumInfoType INFOTYPE_LOCK = new EnumInfoType("INFOTYPE_LOCK", SSRuntimeApiModuleJNI.INFOTYPE_LOCK_get());
  public final static EnumInfoType INFOTYPE_SESSION = new EnumInfoType("INFOTYPE_SESSION", SSRuntimeApiModuleJNI.INFOTYPE_SESSION_get());
  public final static EnumInfoType INFOTYPE_LICENSE = new EnumInfoType("INFOTYPE_LICENSE", SSRuntimeApiModuleJNI.INFOTYPE_LICENSE_get());
  public final static EnumInfoType INFOTYPE_FILE_LIST = new EnumInfoType("INFOTYPE_FILE_LIST", SSRuntimeApiModuleJNI.INFOTYPE_FILE_LIST_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EnumInfoType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EnumInfoType.class + " with value " + swigValue);
  }

  private EnumInfoType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EnumInfoType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EnumInfoType(String swigName, EnumInfoType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EnumInfoType[] swigValues = { INFOTYPE_LOCK, INFOTYPE_SESSION, INFOTYPE_LICENSE, INFOTYPE_FILE_LIST };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

