/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public final class EnumLangID {
  public final static EnumLangID LANGUAGE_SIMPLIFIED_CHINESE = new EnumLangID("LANGUAGE_SIMPLIFIED_CHINESE", SSRuntimeApiModuleJNI.LANGUAGE_SIMPLIFIED_CHINESE_get());
  public final static EnumLangID LANGUAGE_ENGLISH = new EnumLangID("LANGUAGE_ENGLISH", SSRuntimeApiModuleJNI.LANGUAGE_ENGLISH_get());
  public final static EnumLangID LANGUAGE_TRADITIONAL_CHINESE = new EnumLangID("LANGUAGE_TRADITIONAL_CHINESE", SSRuntimeApiModuleJNI.LANGUAGE_TRADITIONAL_CHINESE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EnumLangID swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EnumLangID.class + " with value " + swigValue);
  }

  private EnumLangID(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EnumLangID(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EnumLangID(String swigName, EnumLangID swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EnumLangID[] swigValues = { LANGUAGE_SIMPLIFIED_CHINESE, LANGUAGE_ENGLISH, LANGUAGE_TRADITIONAL_CHINESE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

