/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StFindLicenseRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StFindLicenseRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StFindLicenseRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StFindLicenseRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StFindLicenseRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StFindLicenseRet_RetValue_get(swigCPtr, this);
  }

  public void setData(String value) {
    SSRuntimeApiModuleJNI.StFindLicenseRet_Data_set(swigCPtr, this, value);
  }

  public String getData() {
    return SSRuntimeApiModuleJNI.StFindLicenseRet_Data_get(swigCPtr, this);
  }

  public StFindLicenseRet() {
    this(SSRuntimeApiModuleJNI.new_StFindLicenseRet(), true);
  }

}
