/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StGetVersionRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StGetVersionRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StGetVersionRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StGetVersionRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StGetVersionRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StGetVersionRet_RetValue_get(swigCPtr, this);
  }

  public void setApiVersion(long value) {
    SSRuntimeApiModuleJNI.StGetVersionRet_ApiVersion_set(swigCPtr, this, value);
  }

  public long getApiVersion() {
    return SSRuntimeApiModuleJNI.StGetVersionRet_ApiVersion_get(swigCPtr, this);
  }

  public void setSSVersion(long value) {
    SSRuntimeApiModuleJNI.StGetVersionRet_SSVersion_set(swigCPtr, this, value);
  }

  public long getSSVersion() {
    return SSRuntimeApiModuleJNI.StGetVersionRet_SSVersion_get(swigCPtr, this);
  }

  public StGetVersionRet() {
    this(SSRuntimeApiModuleJNI.new_StGetVersionRet(), true);
  }

}
