/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StGetDeveloperIDRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StGetDeveloperIDRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StGetDeveloperIDRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StGetDeveloperIDRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StGetDeveloperIDRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StGetDeveloperIDRet_RetValue_get(swigCPtr, this);
  }

  public void setDeveloperID(String value) {
    SSRuntimeApiModuleJNI.StGetDeveloperIDRet_DeveloperID_set(swigCPtr, this, value);
  }

  public String getDeveloperID() {
    return SSRuntimeApiModuleJNI.StGetDeveloperIDRet_DeveloperID_get(swigCPtr, this);
  }

  public StGetDeveloperIDRet() {
    this(SSRuntimeApiModuleJNI.new_StGetDeveloperIDRet(), true);
  }

}
