/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StGetArmDeviceInfoRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StGetArmDeviceInfoRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StGetArmDeviceInfoRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StGetArmDeviceInfoRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StGetArmDeviceInfoRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StGetArmDeviceInfoRet_RetValue_get(swigCPtr, this);
  }

  public void setData(StDeviceInfo value) {
    SSRuntimeApiModuleJNI.StGetArmDeviceInfoRet_Data_set(swigCPtr, this, StDeviceInfo.getCPtr(value), value);
  }

  public StDeviceInfo getData() {
    long cPtr = SSRuntimeApiModuleJNI.StGetArmDeviceInfoRet_Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StDeviceInfo(cPtr, false);
  }

  public StGetArmDeviceInfoRet() {
    this(SSRuntimeApiModuleJNI.new_StGetArmDeviceInfoRet(), true);
  }

}
