/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StGetLocalLicenseInfoRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StGetLocalLicenseInfoRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StGetLocalLicenseInfoRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StGetLocalLicenseInfoRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StGetLocalLicenseInfoRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StGetLocalLicenseInfoRet_RetValue_get(swigCPtr, this);
  }

  public void setData(vectorStSlmLicenseInfo value) {
    SSRuntimeApiModuleJNI.StGetLocalLicenseInfoRet_Data_set(swigCPtr, this, vectorStSlmLicenseInfo.getCPtr(value), value);
  }

  public vectorStSlmLicenseInfo getData() {
    long cPtr = SSRuntimeApiModuleJNI.StGetLocalLicenseInfoRet_Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorStSlmLicenseInfo(cPtr, false);
  }

  public StGetLocalLicenseInfoRet() {
    this(SSRuntimeApiModuleJNI.new_StGetLocalLicenseInfoRet(), true);
  }

}
