/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StLicenseLoginRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StLicenseLoginRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StLicenseLoginRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StLicenseLoginRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StLicenseLoginRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StLicenseLoginRet_RetValue_get(swigCPtr, this);
  }

  public void setSlmHandle(long value) {
    SSRuntimeApiModuleJNI.StLicenseLoginRet_slmHandle_set(swigCPtr, this, value);
  }

  public long getSlmHandle() {
    return SSRuntimeApiModuleJNI.StLicenseLoginRet_slmHandle_get(swigCPtr, this);
  }

  public StLicenseLoginRet() {
    this(SSRuntimeApiModuleJNI.new_StLicenseLoginRet(), true);
  }

}
