/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StLocalBindInfoRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StLocalBindInfoRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StLocalBindInfoRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StLocalBindInfoRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StLocalBindInfoRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StLocalBindInfoRet_RetValue_get(swigCPtr, this);
  }

  public void setData(vectorStLocalBindInfo value) {
    SSRuntimeApiModuleJNI.StLocalBindInfoRet_Data_set(swigCPtr, this, vectorStLocalBindInfo.getCPtr(value), value);
  }

  public vectorStLocalBindInfo getData() {
    long cPtr = SSRuntimeApiModuleJNI.StLocalBindInfoRet_Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorStLocalBindInfo(cPtr, false);
  }

  public StLocalBindInfoRet() {
    this(SSRuntimeApiModuleJNI.new_StLocalBindInfoRet(), true);
  }

}
