/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StLocalBindInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StLocalBindInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StLocalBindInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StLocalBindInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeveloperID(String value) {
    SSRuntimeApiModuleJNI.StLocalBindInfo_DeveloperID_set(swigCPtr, this, value);
  }

  public String getDeveloperID() {
    return SSRuntimeApiModuleJNI.StLocalBindInfo_DeveloperID_get(swigCPtr, this);
  }

  public void setNumber(String value) {
    SSRuntimeApiModuleJNI.StLocalBindInfo_Number_set(swigCPtr, this, value);
  }

  public String getNumber() {
    return SSRuntimeApiModuleJNI.StLocalBindInfo_Number_get(swigCPtr, this);
  }

  public void setGuid(String value) {
    SSRuntimeApiModuleJNI.StLocalBindInfo_Guid_set(swigCPtr, this, value);
  }

  public String getGuid() {
    return SSRuntimeApiModuleJNI.StLocalBindInfo_Guid_get(swigCPtr, this);
  }

  public void setLicenseKey(String value) {
    SSRuntimeApiModuleJNI.StLocalBindInfo_LicenseKey_set(swigCPtr, this, value);
  }

  public String getLicenseKey() {
    return SSRuntimeApiModuleJNI.StLocalBindInfo_LicenseKey_get(swigCPtr, this);
  }

  public void setStatus(long value) {
    SSRuntimeApiModuleJNI.StLocalBindInfo_Status_set(swigCPtr, this, value);
  }

  public long getStatus() {
    return SSRuntimeApiModuleJNI.StLocalBindInfo_Status_get(swigCPtr, this);
  }

  public void setVCLock(long value) {
    SSRuntimeApiModuleJNI.StLocalBindInfo_VCLock_set(swigCPtr, this, value);
  }

  public long getVCLock() {
    return SSRuntimeApiModuleJNI.StLocalBindInfo_VCLock_get(swigCPtr, this);
  }

  public StLocalBindInfo() {
    this(SSRuntimeApiModuleJNI.new_StLocalBindInfo(), true);
  }

}
