/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StOfflineGetC2DRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StOfflineGetC2DRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StOfflineGetC2DRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StOfflineGetC2DRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StOfflineGetC2DRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StOfflineGetC2DRet_RetValue_get(swigCPtr, this);
  }

  public void setData(String value) {
    SSRuntimeApiModuleJNI.StOfflineGetC2DRet_Data_set(swigCPtr, this, value);
  }

  public String getData() {
    return SSRuntimeApiModuleJNI.StOfflineGetC2DRet_Data_get(swigCPtr, this);
  }

  public StOfflineGetC2DRet() {
    this(SSRuntimeApiModuleJNI.new_StOfflineGetC2DRet(), true);
  }

}
