/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StSlmLicenseInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StSlmLicenseInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StSlmLicenseInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StSlmLicenseInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLicenseVersion(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_LicenseVersion_set(swigCPtr, this, value);
  }

  public long getLicenseVersion() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_LicenseVersion_get(swigCPtr, this);
  }

  public void setFlag(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Flag_set(swigCPtr, this, value);
  }

  public long getFlag() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Flag_get(swigCPtr, this);
  }

  public void setGuid(String value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Guid_set(swigCPtr, this, value);
  }

  public String getGuid() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Guid_get(swigCPtr, this);
  }

  public void setLicenseID(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_LicenseID_set(swigCPtr, this, value);
  }

  public long getLicenseID() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_LicenseID_get(swigCPtr, this);
  }

  public void setStartTime(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_StartTime_set(swigCPtr, this, value);
  }

  public long getStartTime() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_StartTime_get(swigCPtr, this);
  }

  public void setEndTime(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_EndTime_set(swigCPtr, this, value);
  }

  public long getEndTime() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_EndTime_get(swigCPtr, this);
  }

  public void setSpanTime(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_SpanTime_set(swigCPtr, this, value);
  }

  public long getSpanTime() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_SpanTime_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Timestamp_get(swigCPtr, this);
  }

  public void setSerial(int value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Serial_set(swigCPtr, this, value);
  }

  public int getSerial() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Serial_get(swigCPtr, this);
  }

  public void setConcurrency(int value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Concurrency_set(swigCPtr, this, value);
  }

  public int getConcurrency() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Concurrency_get(swigCPtr, this);
  }

  public void setConcurrencyType(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_ConcurrencyType_set(swigCPtr, this, value);
  }

  public long getConcurrencyType() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_ConcurrencyType_get(swigCPtr, this);
  }

  public void setCount(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Count_get(swigCPtr, this);
  }

  public void setModuleBit(java.math.BigInteger value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_ModuleBit_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getModuleBit() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_ModuleBit_get(swigCPtr, this);
  }

  public void setLockTime(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_LockTime_set(swigCPtr, this, value);
  }

  public long getLockTime() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_LockTime_get(swigCPtr, this);
  }

  public void setFirstUseTime(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_FirstUseTime_set(swigCPtr, this, value);
  }

  public long getFirstUseTime() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_FirstUseTime_get(swigCPtr, this);
  }

  public void setRemainingTimes(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_RemainingTimes_set(swigCPtr, this, value);
  }

  public long getRemainingTimes() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_RemainingTimes_get(swigCPtr, this);
  }

  public void setOfflinePeriod(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_OfflinePeriod_set(swigCPtr, this, value);
  }

  public long getOfflinePeriod() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_OfflinePeriod_get(swigCPtr, this);
  }

  public void setBindNode(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_BindNode_set(swigCPtr, this, value);
  }

  public long getBindNode() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_BindNode_get(swigCPtr, this);
  }

  public void setMaxBindNode(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_MaxBindNode_set(swigCPtr, this, value);
  }

  public long getMaxBindNode() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_MaxBindNode_get(swigCPtr, this);
  }

  public void setLastUpdateTimestamp(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_LastUpdateTimestamp_set(swigCPtr, this, value);
  }

  public long getLastUpdateTimestamp() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_LastUpdateTimestamp_get(swigCPtr, this);
  }

  public void setLastUpdateTimeSN(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_LastUpdateTimeSN_set(swigCPtr, this, value);
  }

  public long getLastUpdateTimeSN() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_LastUpdateTimeSN_get(swigCPtr, this);
  }

  public void setEnable(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_Enable_set(swigCPtr, this, value);
  }

  public long getEnable() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_Enable_get(swigCPtr, this);
  }

  public void setRawSize(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_RawSize_set(swigCPtr, this, value);
  }

  public long getRawSize() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_RawSize_get(swigCPtr, this);
  }

  public void setRomSize(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_RomSize_set(swigCPtr, this, value);
  }

  public long getRomSize() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_RomSize_get(swigCPtr, this);
  }

  public void setPubSize(long value) {
    SSRuntimeApiModuleJNI.StSlmLicenseInfo_PubSize_set(swigCPtr, this, value);
  }

  public long getPubSize() {
    return SSRuntimeApiModuleJNI.StSlmLicenseInfo_PubSize_get(swigCPtr, this);
  }

  public StSlmLicenseInfo() {
    this(SSRuntimeApiModuleJNI.new_StSlmLicenseInfo(), true);
  }

}
