/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StUserDataGetContentRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StUserDataGetContentRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StUserDataGetContentRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StUserDataGetContentRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StUserDataGetContentRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StUserDataGetContentRet_RetValue_get(swigCPtr, this);
  }

  public void setDataBase64(String value) {
    SSRuntimeApiModuleJNI.StUserDataGetContentRet_DataBase64_set(swigCPtr, this, value);
  }

  public String getDataBase64() {
    return SSRuntimeApiModuleJNI.StUserDataGetContentRet_DataBase64_get(swigCPtr, this);
  }

  public StUserDataGetContentRet() {
    this(SSRuntimeApiModuleJNI.new_StUserDataGetContentRet(), true);
  }

}
