/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class StUserDataGetSizeRet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StUserDataGetSizeRet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StUserDataGetSizeRet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_StUserDataGetSizeRet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetValue(long value) {
    SSRuntimeApiModuleJNI.StUserDataGetSizeRet_RetValue_set(swigCPtr, this, value);
  }

  public long getRetValue() {
    return SSRuntimeApiModuleJNI.StUserDataGetSizeRet_RetValue_get(swigCPtr, this);
  }

  public void setSize(long value) {
    SSRuntimeApiModuleJNI.StUserDataGetSizeRet_Size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return SSRuntimeApiModuleJNI.StUserDataGetSizeRet_Size_get(swigCPtr, this);
  }

  public StUserDataGetSizeRet() {
    this(SSRuntimeApiModuleJNI.new_StUserDataGetSizeRet(), true);
  }

}
