/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class vectorStSlmLicenseInfo extends java.util.AbstractList<StSlmLicenseInfo> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorStSlmLicenseInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorStSlmLicenseInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_vectorStSlmLicenseInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorStSlmLicenseInfo(StSlmLicenseInfo[] initialElements) {
    this();
    reserve(initialElements.length);

    for (StSlmLicenseInfo element : initialElements) {
      add(element);
    }
  }

  public vectorStSlmLicenseInfo(Iterable<StSlmLicenseInfo> initialElements) {
    this();
    for (StSlmLicenseInfo element : initialElements) {
      add(element);
    }
  }

  public StSlmLicenseInfo get(int index) {
    return doGet(index);
  }

  public StSlmLicenseInfo set(int index, StSlmLicenseInfo e) {
    return doSet(index, e);
  }

  public boolean add(StSlmLicenseInfo e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, StSlmLicenseInfo e) {
    modCount++;
    doAdd(index, e);
  }

  public StSlmLicenseInfo remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public vectorStSlmLicenseInfo() {
    this(SSRuntimeApiModuleJNI.new_vectorStSlmLicenseInfo__SWIG_0(), true);
  }

  public vectorStSlmLicenseInfo(vectorStSlmLicenseInfo other) {
    this(SSRuntimeApiModuleJNI.new_vectorStSlmLicenseInfo__SWIG_1(vectorStSlmLicenseInfo.getCPtr(other), other), true);
  }

  public long capacity() {
    return SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_clear(swigCPtr, this);
  }

  public vectorStSlmLicenseInfo(int count, StSlmLicenseInfo value) {
    this(SSRuntimeApiModuleJNI.new_vectorStSlmLicenseInfo__SWIG_2(count, StSlmLicenseInfo.getCPtr(value), value), true);
  }

  private int doSize() {
    return SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doSize(swigCPtr, this);
  }

  private void doAdd(StSlmLicenseInfo x) {
    SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doAdd__SWIG_0(swigCPtr, this, StSlmLicenseInfo.getCPtr(x), x);
  }

  private void doAdd(int index, StSlmLicenseInfo x) {
    SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doAdd__SWIG_1(swigCPtr, this, index, StSlmLicenseInfo.getCPtr(x), x);
  }

  private StSlmLicenseInfo doRemove(int index) {
    return new StSlmLicenseInfo(SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doRemove(swigCPtr, this, index), true);
  }

  private StSlmLicenseInfo doGet(int index) {
    return new StSlmLicenseInfo(SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doGet(swigCPtr, this, index), false);
  }

  private StSlmLicenseInfo doSet(int index, StSlmLicenseInfo val) {
    return new StSlmLicenseInfo(SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doSet(swigCPtr, this, index, StSlmLicenseInfo.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SSRuntimeApiModuleJNI.vectorStSlmLicenseInfo_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
