/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virbox;

public class vectorStLocalBindInfo extends java.util.AbstractList<StLocalBindInfo> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorStLocalBindInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorStLocalBindInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SSRuntimeApiModuleJNI.delete_vectorStLocalBindInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorStLocalBindInfo(StLocalBindInfo[] initialElements) {
    this();
    reserve(initialElements.length);

    for (StLocalBindInfo element : initialElements) {
      add(element);
    }
  }

  public vectorStLocalBindInfo(Iterable<StLocalBindInfo> initialElements) {
    this();
    for (StLocalBindInfo element : initialElements) {
      add(element);
    }
  }

  public StLocalBindInfo get(int index) {
    return doGet(index);
  }

  public StLocalBindInfo set(int index, StLocalBindInfo e) {
    return doSet(index, e);
  }

  public boolean add(StLocalBindInfo e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, StLocalBindInfo e) {
    modCount++;
    doAdd(index, e);
  }

  public StLocalBindInfo remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public vectorStLocalBindInfo() {
    this(SSRuntimeApiModuleJNI.new_vectorStLocalBindInfo__SWIG_0(), true);
  }

  public vectorStLocalBindInfo(vectorStLocalBindInfo other) {
    this(SSRuntimeApiModuleJNI.new_vectorStLocalBindInfo__SWIG_1(vectorStLocalBindInfo.getCPtr(other), other), true);
  }

  public long capacity() {
    return SSRuntimeApiModuleJNI.vectorStLocalBindInfo_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SSRuntimeApiModuleJNI.vectorStLocalBindInfo_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SSRuntimeApiModuleJNI.vectorStLocalBindInfo_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SSRuntimeApiModuleJNI.vectorStLocalBindInfo_clear(swigCPtr, this);
  }

  public vectorStLocalBindInfo(int count, StLocalBindInfo value) {
    this(SSRuntimeApiModuleJNI.new_vectorStLocalBindInfo__SWIG_2(count, StLocalBindInfo.getCPtr(value), value), true);
  }

  private int doSize() {
    return SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doSize(swigCPtr, this);
  }

  private void doAdd(StLocalBindInfo x) {
    SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doAdd__SWIG_0(swigCPtr, this, StLocalBindInfo.getCPtr(x), x);
  }

  private void doAdd(int index, StLocalBindInfo x) {
    SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doAdd__SWIG_1(swigCPtr, this, index, StLocalBindInfo.getCPtr(x), x);
  }

  private StLocalBindInfo doRemove(int index) {
    return new StLocalBindInfo(SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doRemove(swigCPtr, this, index), true);
  }

  private StLocalBindInfo doGet(int index) {
    return new StLocalBindInfo(SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doGet(swigCPtr, this, index), false);
  }

  private StLocalBindInfo doSet(int index, StLocalBindInfo val) {
    return new StLocalBindInfo(SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doSet(swigCPtr, this, index, StLocalBindInfo.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SSRuntimeApiModuleJNI.vectorStLocalBindInfo_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
